name: Terraform Local AWS Lab

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: s3,sqs
          DEBUG: 1
          AWS_DEFAULT_REGION: us-east-1

    env:
      AWS_ACCESS_KEY_ID: hbx
      AWS_SECRET_ACCESS_KEY: hbx
      AWS_DEFAULT_REGION: us-east-1
      TF_VAR_localstack_endpoint: http://localhost:4566

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Wait for LocalStack
        run: |
          echo "Aguardando LocalStack iniciar..."
          for i in {1..20}; do
            if curl -s http://localhost:4566/health | grep -q running; then
              echo "LocalStack pronto!"
              break
            fi
            sleep 3
          done

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan